<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "brain_event_frontend"
 *
 * Auto generated by Extension Builder 2018-07-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Brain Events Frontend',
    'description' => 'Frontend plugins for Brain Events',
    'category' => 'plugin',
    'author' => 'Gert Hammes',
    'author_email' => 'gert.hammes@brain-appeal.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'brain_event_connector' => '>=0.4.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
