services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BrainAppeal\CampusEventsFrontend\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/**/Exception.php'
